FROM ollama/ollama

COPY ./run-ollama.sh /tmp/run-ollama.sh

WORKDIR /tmp

RUN chmod +x run-ollama.sh \
    && ./run-ollama.sh

# RUN ollama serve &
# RUN ollama list
# RUN ollama pull llama3

EXPOSE 11434